### PR TITLE
Fix blocking issues related to flutter

### LINKED ISSUE #1478: dartdoc build is failing
This is for the flutter bot:

https://travis-ci.org/dart-lang/dartdoc/jobs/260396830

This happened on the weekly cron job rebuild of dartdoc, so perhaps this was due to a change in the flutter source code?

/cc @jcollins-g

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1478:

- Eliminate excessive stack depth on link checker which occasionally caused stack overflows.
- Use preferredClass in more cases to disambiguate doc links (fixes problems with checked mode)
- Add basic support, and tests for MultiplyInheritedExecutableElements when they come from the analyzer.

### CODE REVIEW

File: lib/dartdoc.dart [hunk 1]
```diff
@@ -366,14 +366,28 @@ class DartDoc {
...
+      // Remove so that we properly count that the file doesn't exist for
+      // the orphan check.
+      visited.remove(fullPath);
       return null;
     }
     visited.add(fullPath);
     Iterable<String> stringLinks = stringLinksAndHref.item1;
     String baseHref = stringLinksAndHref.item2;
 
+    // Prevent extremely large stacks by storing the paths we are using
```
Comment (devoncarew) [inline lib/dartdoc.dart]: kk, good to document this (why we're using this algorithm)
