### PR TITLE
Fix for duplicate libraries in SDK docs

### LINKED ISSUE #1210: api.dartlang shows two dart:math libraries in left nav bar
This is for the 1.18 dev channel

screen shot 2016-07-21 at 9 44 06 am

### PR DESCRIPTION
**Pull request by keertip**
closes #1210 

@pq, @devoncarew

### CODE REVIEW

File: lib/dartdoc.dart [hunk 1]
```diff
@@ -196,7 +196,8 @@ class DartDoc {
       ..sourceFactory = sourceFactory;
 
     if (packageMeta.isSdk) {
-      libraries.addAll(getSdkLibrariesToDocument(sdk, context));
+      libraries
+          .addAll(new Set()..addAll(getSdkLibrariesToDocument(sdk, context)));
```
Comment (pq) [inline lib/dartdoc.dart]: Would be awesome if collections supported a `distinct()` method, so we could just say `getSdkLibrariesToDocument(sdk, context).distinct()`.  That said, a set works in the meantime! 👍

Comment (pq) [inline lib/dartdoc.dart]: Alternatively, I guess `getSdkLibrariesToDocument()` might enforce uniqueness.  Would there be any benefit to doing it there?

**Comment by pq** [comment]
LGTM.
