### PR TITLE
Fix issue with generation of 'null' value enum fields

### LINKED ISSUE #1445: The values for each value of the `BoxFit` enum all say they are `const BoxFit(null)`
The values for each value of the `BoxFit` enum all say they are `const BoxFit(null)`:

https://docs.flutter.io/flutter/painting/BoxFit-class.html

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1445.  Adding Paul to the reviewers as a comment in ConstFieldElementImpl suggested he might have context as to whether the [change to how we compute enum indexes](https://github.com/dart-lang/dartdoc/compare/null-enums?expand=1#diff-4d22582de7e25fdddcfff99652835a1eR2142) is actually an improvement over some variant of the original hack.

### CODE REVIEW

**Comment by jcollins-g** [comment]
AppVeyor builds are pub errors and I don't have access to retry them.  @devoncarew?

File: lib/src/model.dart [hunk 1]
```diff
@@ -2163,21 +2135,32 @@ abstract class ModelElement extends Nameable
...
-          if (index != null) {
-            assert(getter != null);
-            newModelElement =
-                new EnumField.forConstant(index, e, library, getter);
-          } else {
-            if (e.enclosingElement.isEnum) {
-              newModelElement = new EnumField(e, library, getter, setter);
+          if (e.enclosingElement.isEnum) {
+            int index =
+                e.computeConstantValue()?.getField('index')?.toIntValue();
```
Comment (stereotype441) [inline lib/src/model.dart]: This definitely works but it took a bit of thinking before I understood why.  Essentially what's happening here is that the fields in an enum class `E` are all static fields having type `E`, except for the two "special" fields `index` (a non-static field having type `int`) and `values` (a static field having type  `List<E>`).  You only want your new behavior for the non-special fields, and it works because only the type `E` has a non-static member `index` whose value is an `int`; the types `int` and `List<E>` don't.

If I'm understanding the code correctly there's a getter `FieldElement.isEnumConstant` that does what you want.  So I think you could replace lines 2140-2161 with something like:

```dart
if (e.isEnumConstant) {
  int index = e.computeConstantValue().getField('index').toIntValue();
  newModelElement = new EnumField.forConstant(index, e, library, getter);
} else if (e.enclosingElement.isEnum) {
  newModelElement = new EnumField(e, library, getter, setter);
} else {
  newModelElement = new Field(e, library, getter, setter);
}
```

Comment (jcollins-g) [inline lib/src/model.dart]: Oh, that's so much better.  This logic is what I intended: if I had seen/thought to look for e.isEnumConstant I would have written it exactly like this.  Thanks!

File: lib/src/model.dart [hunk 2]
```diff
@@ -458,7 +458,6 @@ class Class extends ModelElement implements EnclosedElement {
         ..addAll(constructors)
         ..addAll(staticMethods)
         ..addAll(staticProperties)
-        ..addAll(allInstanceMethods)
```
Comment (keertip) [inline lib/src/model.dart]: why was this removed?

Comment (jcollins-g) [inline lib/src/model.dart]: It was a duplicate, it was already addAll on line 454.

Comment (keertip) [inline lib/src/model.dart]: that line is not shown in the review :)
