### PR TITLE
fix type info for Map with generics

### LINKED ISSUE #917: Map type is sometimes shown with only one generic argument type
for the invocation-class [0] the Map type for the named arguments states that it only has one generic argument. I'm guessing the second one is `dynamic`, but it's not clear.

[0] https://api.dartlang.org/1.12.1/dart-core/Invocation-class.html

### LINKED ISSUE #919: Missing 'dynamic' in type parameters
`Map<Symbol>` below should be `Map<Symbol, dynamic>`
Omit the type parameters only when all are dynamic.

https://api.dartlang.org/1.12.1/dart-core/Function/apply.html
```
dynamic apply( 
    Function function,
    List positionalArguments,
    [Map<Symbol> namedArguments]
)
```

### PR DESCRIPTION
**Pull request by keertip**
closes #919 
closes #917

### CODE REVIEW

File: test/model_test.dart [hunk 1]
```diff
@@ -839,6 +844,11 @@ String topLevelFunction(int param1, bool param2, Cool coolBeans,
       expect(isGreaterThan.modelType.createLinkedReturnTypeName(), 'bool');
     });
 
+    test('parameter has generics in signature', () {
+      expect(testGeneric.parameters[0].modelType.linkedName,
+          'Map&lt;String,dynamic&gt;');
```
Comment (sethladd) [inline test/model_test.dart]: should we put a space after the comma ?

Comment (keertip) [inline test/model_test.dart]: yes, we should. Thought I had added it.

**Comment by sethladd** [comment]
If you don't mind rebasing, please do.

other, lgtm! And thanks!
