### PR TITLE
Fix members not being marked as inherited in sidebars - Fixes #2472

### LINKED ISSUE #2472: Inherited methods are no longer italics in the right sidebar (regression)
Contrast the right sidebar in these two:
https://api.flutter.dev/flutter/rendering/RenderClipOval-class.html
https://master-api.flutter.dev/flutter/rendering/RenderClipOval-class.html

The methods that are inherited are italics in the old sidebar, and look exactly like overridden methods in the new sidebar. I noticed this in particular because now noSuchMethod looks like it's overridden by everyone and part of every API.

### PR DESCRIPTION
**Pull request by parlough**
**Inherited issue:**
This switches to sharing the sections with inherited features between `class` and `enum`. 

Fixes #2472 

**Operator issue:**

Handling of checking if all instance operators are inherited was messed up, resulting in the operators section always being marked as inherited(multiple times in fact) and being italicized. This standardizes it to match the behavior of methods.

The second commit addresses this issue.

### CODE REVIEW

File: lib/src/model/class.dart [hunk 1]
```diff
@@ -85,6 +85,10 @@ class Class extends Container
   Iterable<Operator> get instanceOperators =>
       quiver.concat([super.instanceOperators, inheritedOperators]);
 
+  @override
+  bool get publicInheritedInstanceOperators =>
+      instanceOperators.every((f) => f.isInherited);
```
Comment (jcollins-g) [inline lib/src/model/class.dart:90]: Good catch.  I don't think members of `instanceOperators` are guaranteed to be public even if they happen to be now.   Wrapping in model_utils.filterNonPublic() seems prudent in case of changes.

These booleans really should be prefixed with "has" but given as this is consistent with methods, I'll save that adjustment for the next time through here.

File: lib/src/model/container.dart [hunk 2]
```diff
@@ -74,7 +75,10 @@ abstract class Container extends ModelElement with TypeParameters {
   /// This is only used in mustache templates.
   bool get publicInheritedInstanceMethods => false;
 
-  Iterable<Operator> get publicInheritedInstanceOperators => [];
+  /// Whether all instance operators are inherited.
+  ///
+  /// This is only used in mustache templates.
```
Comment (jcollins-g) [inline lib/src/model/container.dart:80]: it's not restricted to them though, so probably this little comment can be deleted.

File: lib/templates/html/_sidebar_for_container.html [hunk 3]
```diff
@@ -64,7 +66,9 @@
     <li>{{{ linkedName }}}</li>
     {{/publicInstanceOperatorsSorted}}
     {{/hasPublicInstanceOperators}}
+    {{/isExtension}}
 
+    {{#isClassOrExtension}}
```
Comment (jcollins-g) [inline lib/templates/html/_sidebar_for_container.html:71]: mustache may not require it but closing this section seems like a good idea

**Review by jcollins-g — CHANGES_REQUESTED** [review]
Great work!  Please add at least a test for the publicInheritedInstanceOperators method.  I think an end-to-end verification is probably redundant but optionally you could add that as well to double-check rendering.

File: lib/templates/html/_sidebar_for_container.html (hunk 3 above)
Comment (parlough) [reply lib/templates/html/_sidebar_for_container.html:71]: I think this one is closed later on in the file, it just isn't included in the changes as it was pre-existing.

**Comment by parlough** [comment]
> Great work!  Please add at least a test for the publicInheritedInstanceOperators method.  I think an end-to-end verification is probably redundant but optionally you could add that as well to double-check rendering.

Thanks for the feedback! I'll address the desired changes and add the tests sometime later today.

File: lib/src/model/class.dart (hunk 1 above)
Comment (parlough) [reply lib/src/model/class.dart]: Seems we already had this with a `publicInstanceOperators` getter, so I switched to using that. Thanks for catching this.

File: lib/src/model/container.dart (hunk 2 above)
Comment (parlough) [reply lib/src/model/container.dart]: I've removed it from this getter and the related nearby ones as well.

**Comment by parlough** [comment]
@jcollins-g I believe I have addressed your raised issues as well as added some small tests. Let me know if you'd like to see any other changes. Thanks :1st_place_medal:

File: lib/templates/html/_sidebar_for_container.html (hunk 3 above)
Comment (jcollins-g) [reply lib/templates/html/_sidebar_for_container.html:71]: oh, you're right I missed that.

**Review by jcollins-g — APPROVED** [review]
approved, will land once green.
