### PR TITLE
fix for generating docs for exported libs

### LINKED ISSUE #595: NPE when generating docs
To repro: `dart tool/doc_packages.dart bwu_utils_dev`.

```
NoSuchMethodError: method not found: 'split'
Receiver: null
Arguments: ["/"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      HtmlGeneratorInstance.generateClass (package:dartdoc/src/html_generator.dart:283:36)
#3      HtmlGeneratorInstance.generate.<generate_async_body>.<anonymous closure>.<anonymous closure> (package:dartdoc/src/html_generator.dart:141:9)
#4      List.forEach (dart:core-patch/growable_array.dart:234)
#5      HtmlGeneratorInstance.generate.<generate_async_body>.<anonymous closure> (package:dartdoc/src/html_generator.dart:140:22)
#6      List.forEach (dart:core-patch/growable_array.dart:234)
#7      HtmlGeneratorInstance.generate.<generate_async_body> (package:dartdoc/src/html_generator.dart:137:23)
```

See also https://github.com/dart-lang/dartdoc/pull/594/files#diff-b33dc7f777bad2309ac40d590d4a83c1R282

### PR DESCRIPTION
**Pull request by keertip**
@devoncarew 

closes #595

### CODE REVIEW

File: lib/src/model.dart [hunk 1]
```diff
@@ -394,25 +394,23 @@ class Package {
...
       return _libraries.any((lib) => lib.element == e.element);
+    }
+
+    Element el;
+    if (e.element is ClassMemberElement ||
+        e.element is PropertyAccessorElement) {
+      el = e.element.enclosingElement;
+    } else if (e.element is TopLevelVariableElement) {
+      TopLevelVariableElement variable = (e.element as TopLevelVariableElement);
+      if (variable.getter != null) el = variable.getter;
```
Comment (devoncarew) [inline lib/src/model.dart]: I think we want to use braces in these if-else blocks.
