### PR TITLE
Fix implementation chain with internal private classes

### LINKED ISSUE #2094: Inheritance doesn't match Implementors for ErrorDescription/DiagnosticsProperty (probably due to generics?)
https://api.flutter.dev/flutter/foundation/ErrorDescription-class.html says it inherits from "DiagnosticsProperty", but https://api.flutter.dev/flutter/foundation/DiagnosticsProperty-class.html does not list "ErrorDescription" in its list of implementors. The lack of symmetry is confusing.

### LINKED ISSUE #2290: Implementers section missing on RestorableValue.
https://master-api.flutter.dev/flutter/widgets/RestorableInt-class.html says:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<int> > RestorableValue<int> > RestorableNum<int> > RestorableInt
```

Click on `RestorableNum`, you get https://master-api.flutter.dev/flutter/widgets/RestorableNum-class.html:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<T> > RestorableValue<T> > RestorableNum
Implementers
RestorableDouble, RestorableInt
```

Click on `RestorableValue`, you get https://master-api.flutter.dev/flutter/widgets/RestorableValue-class.html:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<T> > RestorableValue
```

...with no "Implementers" section!

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #2290

Before this fix, RestorableValue lists no implementors. After this fix, RestorableValue lists the following implementors:

> RestorableBool, RestorableNum, RestorableString

Fixes #2094

Before this fix, DiagnosticsProperty lists the following implementors:

> ColorProperty, DiagnosticsDebugCreator, EnumProperty, ErrorSpacer, FlagProperty, FlagsSummary, IconDataProperty, IterableProperty, MessageProperty, ObjectFlagProperty, ShortcutMapProperty, StringProperty, TransformProperty

After this fix, DiagnosticsProperty lists the following implementors:

> ErrorDescription, ErrorHint, ErrorSummary, DoubleProperty, IntProperty, ColorProperty, DiagnosticsDebugCreator, EnumProperty, ErrorSpacer, FlagProperty, FlagsSummary, IconDataProperty, IterableProperty, MessageProperty, ObjectFlagProperty, ShortcutMapProperty, StringProperty, TransformProperty

### CODE REVIEW

File: lib/src/model/package_graph.dart [hunk 1]
```diff
@@ -202,7 +203,10 @@ class PackageGraph {
       allInheritableElements = {};
 
   /// A mapping of the list of classes which implement each class.
-  final Map<Class, List<Class>> _implementors = {};
+  final Map<Class, List<Class>> _implementors = LinkedHashMap(
+      equals: (Class a, Class b) =>
+          a.hrefAllowingNonCanonical == b.hrefAllowingNonCanonical,
```
Comment (jcollins-g) [inline lib/src/model/package_graph.dart:208]: We need to take into account definingLibrary here.  Otherwise, we're likely to duplicate classes that are reexported through multiple private libraries.

**Review by jcollins-g — CHANGES_REQUESTED** [review]

File: lib/src/model/package_graph.dart (hunk 1 above)
Comment (jcollins-g) [reply lib/src/model/package_graph.dart:208]: Unless I'm missing something and this is covered by other means.

Comment (srawlins) [reply lib/src/model/package_graph.dart]: Ah ha, using ModelElement.from instead.

**Review by jcollins-g — APPROVED** [review]
