### PR TITLE
Fix truncation in middle of links for constants

### LINKED ISSUE #1535: Bizarre mid-word hyperlinking issue
On the [SystemChannels.platform] page, there's a link to "OptionalMessageChannel", at least there should be, but somehow it's becoming a link to "MessageChannel", with only half the word hyperlinked???￼

https://master-docs-flutter-io.firebaseapp.com/flutter/services/SystemChannels/platform-constant.html

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1535.  Third breakout from #1524 -- necessary because #1535 becomes much worse with the overhaul as more classes are made linkable.  Without this change #1535 would become a P1 post-overhaul as Flutter docs would begin generating broken links and warning about them.

Rearranges how constantValue is calculated, factoring it out into GetterSetterCombo and substituting any links in after truncating and escaping, rather than before.

### CODE REVIEW

File: lib/src/model.dart [hunk 1]
```diff
@@ -1441,11 +1427,34 @@ abstract class GetterSetterCombo implements ModelElement {
...
+        var string = v.substring(v.indexOf('=') + 1, v.length).trim();
+        _constantValueBase =
+            const HtmlEscape(HtmlEscapeMode.UNKNOWN).convert(string);
+      }
+    }
+    return _constantValueBase;
+  }
+
+  String linkifyWithModelType(String text) {
+    RegExp r = new RegExp("\\b${modelType.name}\\b");
```
Comment (devoncarew) [inline lib/src/model.dart]: Is this called frequently? If so, we may want to cache the regexp in an instance field.

Comment (jcollins-g) [reply lib/src/model.dart]: This method is not called very often per GetterSetterCombo (maybe twice?).  Probably not worth it at this point.
