### PR TITLE
Fix rel canonical link

### LINKED ISSUE #2122: Canonical URL calculation is off for top-level functions
dartdoc: `0.30.0+1`

example top-level function:
- source: https://github.com/dart-lang/pana/blob/master/lib/src/utils.dart#L191-L209
- documentation: https://pub.dartlang.org/documentation/pana/0.12.2/pana/prettyJson.html
arguments: `--rel-canonical-prefix https://pub.dartlang.org/documentation/pana/0.12.2`

expected content in HTML:
- `<link rel="canonical" href="https://pub.dartlang.org/documentation/pana/0.12.2/pana/prettyJson.html">`

actual content in HTML:
- `<link rel="canonical" href="https://pub.dartlang.org/documentation/pana/0.12.2/../pana/prettyJson.html">`

(note the `/../` segment between `/0.12.2/` and `/pana/`)

### PR DESCRIPTION
**Pull request by jdkoren**
Fixes #2122

### CODE REVIEW

File: test/dartdoc_test.dart [hunk 1]
```diff
@@ -406,5 +406,19 @@ void main() {
...
+      Dartdoc dartdoc = await buildDartdoc(
+          ['--rel-canonical-prefix', prefix], testPackageMinimumDir, tempDir);
+      await dartdoc.generateDocsBase();
+
+      File file = File(path.join(tempDir.path, 'small', 'small-library.html'));
+      expect(file.existsSync(), isTrue);
+      expect(
+          file.readAsStringSync(),
+          contains(
+              '<link rel="canonical" href="$prefix/small/small-library.html">'));
```
Comment (jcollins-g) [inline test/dartdoc_test.dart]: This seems like it should work but I would suggest verifying it for links at root and two levels down in the directory structure.

Comment (jdkoren) [reply test/dartdoc_test.dart]: Added another file to be checked in the test

Comment (jdkoren) [reply test/dartdoc_test.dart]: Oops, found a mistake in the test, will push up another commit.
