### PR TITLE
eliminate crash on warnings generated by README.md

### LINKED ISSUE #1409: Regression: new warning system unable to handle warnings caused by package README.md
This version refuses to generate docs for Intl due to changes in

https://github.com/dart-lang/dartdoc/commit/47b60b4f17ebd45f73b535c24dc91086cde12ac4

There are two libraries, one for dart:io and one for dart:html which both re-export the same thing, and it considers this ambiguous. Even if it was ambiguous, that's hardly a reason to refuse to generate documentation.

### PR DESCRIPTION
**Pull request by jcollins-g**
fix #1409.

This fixes the bug by eliminating the second pathway to _renderMarkdownToHtml, forcing packages down the same path as every other Documentable.

### CODE REVIEW

File: lib/src/markdown_processor.dart [hunk 1]
```diff
@@ -300,7 +301,17 @@ Element _getRefElementFromCommentRefs(
...
-        return ref.identifier.staticElement;
+        Element refElement = ref.identifier.staticElement;
+        if (refElement is PropertyAccessorElement) {
+          // yay we found an accessor that wraps a const, but we really
+          // want the top-level field itself
+          refElement = (refElement as PropertyAccessorElement).variable;
+        }
+        if (refElement is PrefixElement) {
+          // We found a prefix element, but what we really want is the library element.
+          refElement = (refElement as PrefixElement).enclosingElement;
```
Comment (jcollins-g) [inline lib/src/markdown_processor.dart]: This is actually a second bug that was lurking behind the first one: commentRefs can contain PrefixElements.
