### PR TITLE
Fix issues with source code HTML of fields and accessors

### LINKED ISSUE #2202: Implementation section drops semi-colons for late fields
When NNBD is enabled we're losing semicolons for fields, for some reason.

Screen Shot 2020-05-06 at 2 40 15 PM

### PR DESCRIPTION
**Pull request by CaptainIRS**
Fixes flutter/flutter#67802 
* The issue occurs as models for Field and Accessor override the `sourceCode` getter but don't escape special characters in their implementation. This is now fixed.

Fixes #2202 
* The issue occurs as the `ASTNode` which is obtained for `FieldElement` is not high enough up the syntax tree to include the semicolon. So the calculated `_sourceEnd` doesn't include the semicolon. ~So it is now added manually.~ So, in that case, the parent node that contains the entire statement is obtained to calculate the offset and end.

### CODE REVIEW

File: lib/src/model/model_node.dart [hunk 1]
```diff
@@ -67,6 +67,12 @@ class ModelNode {
         source = model_utils.stripIndentFromSource(source);
         source = model_utils.stripDartdocCommentsFromSource(source);
 
+        // The calculated source code end for field elements doesn't include
+        // the semicolon for field elements, so it has to be added manually
+        if (element is FieldElement) {
+          source += ';';
```
Comment (jcollins-g) [inline lib/src/model/model_node.dart:73]: This seems reasonable enough unless analyzer experts have a better idea of how to solve this.  I had thought it was just late fields that were broken, didn't realize it was all simple fields.  @scheglov ?

**Review by jcollins-g — COMMENTED** [review]
will approve once the P0 fix is landed and out (#2404)

File: lib/src/model/model_node.dart (hunk 1 above)
Comment (scheglov) [reply lib/src/model/model_node.dart:73]: This is mostly up to you. What `AstNode` do you expect to get for each documentable entity? For methods this is probably uncontroversial - `MethodDeclaration`. For fields - probably `VariableDeclaration`, with parent `VariableDeclarationList`, with parent `FieldDeclaration`. But you can have more than one field in one `FieldDeclaration`, so the whole idea of extracting "source code" for a field seems suspicious to me. Not knowing what exactly you are doing with it, I cannot say that it is definitely wrong though.

**Comment by CaptainIRS** [comment]
I've found another issue with the source code HTML where it just removes the all previous lines when variable declaration spans across many lines.

I've modified the fix to be less hacky and still be able to fix all the 2 issues mentioned previously and this new one in a more elegant fashion.

File: lib/src/model/model_node.dart [hunk 2]
```diff
@@ -47,11 +45,25 @@ class ModelNode {
 
   String get sourceCode {
     if (_sourceCode == null) {
-      if (_sourceOffset != null) {
+      if (_sourceNode?.offset != null) {
+        var sourceNode = _sourceNode;
```
Comment (jcollins-g) [inline lib/src/model/model_node.dart:49]: optional: might be less confusing to name `sourceNode` something else

**Review by jcollins-g — APPROVED** [review]

File: lib/src/model/model_node.dart (hunk 2 above)
Comment (CaptainIRS) [reply lib/src/model/model_node.dart:49]: Sure! I'm thinking of renaming it to `astNode`. Would that be fine?

Comment (jcollins-g) [reply lib/src/model/model_node.dart:49]: Maybe 'enclosingSourceNode' or something along those lines, since it is based on `_sourceNode` and may be computed based on parent nodes?

Comment (CaptainIRS) [reply lib/src/model/model_node.dart]: Done!
