### PR TITLE
Fix unstable template runtime renderer generation

### LINKED ISSUE #2751: check build verification for templates are unstable
e.g. https://github.com/dart-lang/dartdoc/pull/2750/checks?check_run_id=3374650937

### PR DESCRIPTION
**Pull request by parlough**
Fixes #2751

### CODE REVIEW

File: tool/mustachio/codegen_runtime_renderer.dart [hunk 1]
```diff
@@ -587,7 +587,7 @@ renderValue:
     _buffer.write('const _invisibleGetters = {');
     for (var class_ in _invisibleGetters.keys.toList()..sort()) {
       _buffer.write("'$class_':");
-      var getters = _invisibleGetters[class_]!;
+      var getters = _invisibleGetters[class_]!.toList()..sort();
```
Comment (srawlins) [inline tool/mustachio/codegen_runtime_renderer.dart:590]: \*facepalm\* I thought this was going to be complicated to fix.

Thanks!

**Review by srawlins — APPROVED** [review]
