### PR TITLE
Fix templates in one liners

### LINKED ISSUE #2272: Class overview contains {@template xxx} of properties/methods
When the doc comment of a property or method within a class starts with `{@template fff}`, that string appears in the overview doc of the enclosing class:

https://master-api.flutter.dev/flutter/widgets/SliverFixedExtentList-class.html

image

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #2272.

In a reexport chain where the origin is private and the symbol is visible in more than one library, the oneLineDoc won't be properly precached and can leave template detritus behind.

### CODE REVIEW

File: test/end2end/model_test.dart [hunk 1]
```diff
@@ -628,11 +628,22 @@ void main() {
...
+      expect(
+          ClassTemplateOneLiner.oneLineDoc,
+          equals(
+              'I had better not have a template directive in my one liner.'));
     });
 
     test('renders a macro defined within a enum', () {
       expect(macroReferencedHere.documentationAsHtml,
           contains('This is a macro defined in an Enum accessor.'));
+      [1, 2, 3].whereType();
```
Comment (srawlins) [inline test/end2end/model_test.dart:646]: Eh?

**Review by srawlins — APPROVED** [review]

File: test/end2end/model_test.dart (hunk 1 above)
Comment (jcollins-g) [reply test/end2end/model_test.dart:646]: what in the.... I have no idea what this is from.

Comment (jcollins-g) [reply test/end2end/model_test.dart:646]: sometimes i think vs code is randomly inserting things on me, in part because I haven't yet managed to get the control scheme to be truly vim like.
