### PR TITLE
Fix bug where --version didn't do anything

### LINKED ISSUE #1692: --version is broken
```
$ pub global activate dartdoc 0.19.0
Package dartdoc is currently active at version 0.19.0.
[...]

$ pub global run dartdoc --version
Generate HTML documentation for Dart libraries.

[... continues with help]
```

In the help page:
```
    --version                                     Display the version for dartdoc.
```

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1692.

### CODE REVIEW

File: bin/dartdoc.dart [hunk 1]
```diff
@@ -97,8 +97,15 @@ void _printHelpAndExit(ArgParser parser, {int exitCode: 0}) {
...
 
+/// Print usage information on invalid command lines.
 void _printUsageAndExit(ArgParser parser, {int exitCode: 0}) {
   print('Usage: dartdoc [OPTIONS]\n');
   print(parser.usage);
   exit(exitCode);
 }
+
+/// Print version information.
+void _printVersionAndExit(ArgParser parser, {int exitCode: 0}) {
```
Comment (devoncarew) [inline bin/dartdoc.dart]: is `exitCode` ever passed in by clients?

File: lib/dartdoc.dart [hunk 2]
```diff
@@ -11,6 +11,7 @@ library dartdoc;
 import 'dart:async';
 import 'dart:convert';
 import 'dart:io';
+import 'dart:mirrors';
```
Comment (devoncarew) [inline lib/dartdoc.dart]: why was this added?

File: tool/grind.dart [hunk 3]
```diff
@@ -67,7 +67,7 @@ Future<FlutterRepo> get cleanFlutterRepo async {
     await cleanFlutterDir.parent.create(recursive: true);
     assert(_lockFuture == null);
     _lockFuture = new File(pathLib.join(cleanFlutterDir.parent.path, 'lock'))
-        .openSync(mode: FileMode.WRITE)
+        .openSync(mode: FileMode.write)
```
Comment (devoncarew) [inline tool/grind.dart]: This will mean that dartdoc can only run on the very very latest sdk; you might want to just live with deprecation warnings for a while.

File: bin/dartdoc.dart (hunk 1 above)
Comment (jcollins-g) [reply bin/dartdoc.dart]: removed

File: lib/dartdoc.dart (hunk 2 above)
Comment (jcollins-g) [reply lib/dartdoc.dart]: leftover from an attempt to automatically read the version number from pubspec.yaml.

File: tool/grind.dart (hunk 3 above)
Comment (jcollins-g) [reply tool/grind.dart]: There are enough other times I've done this that it probably is already required; updated minimums on pubspec.yaml.
