### PR TITLE
Prevent private or non-canonical elements from ever generating links

### LINKED ISSUE #1588: dartdoc generates broken links to private classes in constant declarations
Introduced in #1585.  href generation should simply refuse to generate for a private link; we're to the point now where that's actually a better choice than most of the special casing.

screenshot from 2018-01-10 09 27 12

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1588.  First part of a long awaited refactor to rationalize how we calculate links, but moved up to fix a regression.

### CODE REVIEW

**Comment by jcollins-g** [comment]
test added.

**Comment by kevmoo** [comment]
> test added.

gracias

File: lib/src/model.dart [hunk 1]
```diff
@@ -654,8 +661,11 @@ class Class extends ModelElement
 
   @override
   String get href {
-    if (canonicalLibrary == null) return null;
-    return '${canonicalLibrary.dirName}/$fileName';
+    if (!identical(canonicalModelElement, this))
```
Comment (devoncarew) [inline lib/src/model.dart]: nit: braces for the if statement body

File: lib/src/model.dart [hunk 2]
```diff
@@ -1132,8 +1142,11 @@ class Constructor extends ModelElement
 
   @override
   String get href {
-    if (canonicalLibrary == null) return null;
-    return '${canonicalLibrary.dirName}/${_constructor.enclosingElement.name}/$name.html';
+    if (!identical(canonicalModelElement, this))
+      return canonicalModelElement?.href;
```
Comment (devoncarew) [inline lib/src/model.dart]: here as well, and below

File: lib/src/model.dart (hunk 1 above)
Comment (devoncarew) [reply lib/src/model.dart]: Just for clarity, if this element is not the canonical one, we generate a link to the canonical one?

File: test/model_test.dart [hunk 3]
```diff
@@ -1920,6 +1922,10 @@ String topLevelFunction(int param1, bool param2, Cool coolBeans,
       expect(aStaticConstField.constantValue, '&quot;A Constant Dog&quot;');
     });
 
+    test('privately constructed constants are unlinked', () {
```
Comment (devoncarew) [inline test/model_test.dart]: 👍

File: lib/src/model.dart (hunk 1 above)
Comment (jcollins-g) [reply lib/src/model.dart]: Correct.  While you could infer that from the code previously with all the "canonicalEnclosingElement" stuff, the modification here is intended to make that more clear and to make the object being linked to actually responsible for its own link generation.

Most of the broken link bugs I've seen either were attributable to bugs in how this worked, or were made harder to fix because of it (like this one).  Now elements no longer point blindly into the filesystem hoping that the model really has a canonical element that matches, but we actually look up the element.

Comment (jcollins-g) [reply lib/src/model.dart]: I've got a second change on deck to eliminate the copypasta of hrefs everywhere; if possible I'd prefer to fix the braces there.

Comment (devoncarew) [reply lib/src/model.dart]: sgtm
