### PR TITLE
Display null safety tag only on migrated packages

### LINKED ISSUE #2403: null-safety annotations on non-migrated packages
Reproduction steps:
```
# Extract package:retry version 3.0.1
$ curl -L https://storage.googleapis.com/pub-packages/packages/retry-3.0.1.tar.gz | tar -xz
$ pub get

# Get dartdoc from git
$ mkdir /source/dartdoc
$ git clone https://github.com/dart-lang/dartdoc.git /source/dartdoc
$ cd /source/dartdoc; pub get; cd -;

# Generate docs
$ dart /source/dartdoc/bin/dartdoc.dart 
```

Notice that the `pubspec.yaml` for `package:retry` has:
```
environment:
  sdk: ">=2.0.0 <3.0.0"
```

And `.dart_tool/package_config.json` specifies language version 2.0 for `package:retry`:
```js
{
  "configVersion": 2,
  "packages": [
    /* various other dependencies, mostly test and it's transitive dependencies, omitted here */
    {
      "name": "retry",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.0" // <-- language version 2.0, hence, no library in package:retry supports null-safety
    }
  ],
  "generated": "2020-10-21T10:44:27.912220Z",
  "generator": "pub",
  "generatorVersion": "2.10.0"
}
```

-----------------

**Unexpected result:**

3PjXUKmqd6fA2M4

While it is correct that the [`retry` function cannot return `null`](https://github.com/google/dart-neats/blob/d3187564c166b94bb65a3c5360db730f7f94ce2c/retry/lib/retry.dart#L174-L188), the package is not migrated to null-safety, so should we really be adding any sort of null-safety tag here?

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #2403.  Filing #2410 for the port to AnalysisContextCollection originally anticipated to solve this, and #2409 for removing the null safety tag on individual symbols.

In addition to the end-to-end test, spot checked with  `PACKAGE_NAME=collection PACKAGE_VERSION=1.15.0-nullsafety.4 grind serve-pub-package` and ` PACKAGE_NAME=collection grind serve-pub-package` and verified pages appeared correctly.

### CODE REVIEW

**Review by scheglov — APPROVED** [review]

File: lib/src/model/package_builder.dart [hunk 1]
```diff
@@ -23,15 +23,17 @@ import 'package:analyzer/src/generated/source_io.dart';
...
-import 'package:dartdoc/src/model/model.dart';
+import 'package:dartdoc/src/model/model.dart' hide Package;
 import 'package:dartdoc/src/quiver.dart' as quiver;
 import 'package:dartdoc/src/package_config_provider.dart';
 import 'package:dartdoc/src/package_meta.dart'
     show PackageMeta, PackageMetaProvider;
 import 'package:dartdoc/src/render/renderer_factory.dart';
 import 'package:dartdoc/src/special_elements.dart';
 import 'package:meta/meta.dart';
+// TODO(jcollins-g): do not directly import path, use ResourceProvider instead
```
Comment (srawlins) [inline lib/src/model/package_builder.dart:34]: Ooh good call. I had an idea in my head to grep for path imports and clean them up.

**Review by srawlins — APPROVED** [review]
