### PR TITLE
Fix for issue with references in parameters and return type pointing …

### LINKED ISSUE #1160: Flutter: dartdocs gets wrong class for "CommonFinders"
We have two `find` top-level members:

http://docs.flutter.io/flutter/flutter_test/find.html
http://docs.flutter.io/flutter/flutter_driver/find-constant.html

Both are of type "CommonFinders", but those are different types. Yet they both point to the same class definition:
http://docs.flutter.io/flutter/flutter_driver/CommonFinders-class.html

This is wrong.

The two source files are:
https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/finders.dart
https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart

### LINKED ISSUE #1195: Flutter docs point to the wrong Point
The links in http://docs.flutter.io/flutter/dart-ui/Point-class.html target the Point class from dart:math rather than the dart_ui Point class. Likewise for the Canvas docs and (I would guess) other classes that refer to Point.

(From https://github.com/flutter/flutter/issues/4884)

### PR DESCRIPTION
**Pull request by keertip**
…to wrong element with same name

closes #1195, 
closes #1160 

@devoncarew

### CODE REVIEW

File: lib/src/model.dart [hunk 1]
```diff
@@ -1653,6 +1653,19 @@ abstract class ModelElement implements Comparable, Nameable, Documentable {
     return '<a ${classContent}href="${href}">$name</a>';
   }
 
+  // TODO: consolidate all the find library methods
```
Comment (devoncarew) [inline lib/src/model.dart]: please add your username here

File: lib/src/model.dart [hunk 2]
```diff
@@ -1653,6 +1653,19 @@ abstract class ModelElement implements Comparable, Nameable, Documentable {
...
+  Library _findLibraryFor(Element e) {
+    var eelement = e.getAncestor((l) => l is LibraryElement);
```
Comment (devoncarew) [inline lib/src/model.dart]: `eelement` ==> `element` ?

**Comment by devoncarew** [comment]
lgtm
