### PR TITLE
fix return type not showing if Future

### LINKED ISSUE #1008: Missing return type in IOSink close, flush
Clearly a `Future`

screen shot 2015-10-29 at 1 41 55 pm
screen shot 2015-10-29 at 1 42 01 pm

### PR DESCRIPTION
**Pull request by keertip**
Closes #1008

### CODE REVIEW

File: lib/src/model.dart [hunk 1]
```diff
@@ -2032,7 +2032,7 @@ class ElementType {
     // not TypeParameterType or Void or Union type
     if (isParameterizedType) {
       if (typeArguments.every((t) => t.linkedName == 'dynamic')) {
-        _linkedName = '';
+        _linkedName = buf.toString();
```
Comment (kevmoo) [inline lib/src/model.dart]: why not `return buf.toString();` ?

Comment (keertip) [inline lib/src/model.dart]: Storing it so that subsequent calls can be faster.

Comment (kevmoo) [inline lib/src/model.dart]: Ah! It's an instance var! Sorry. :grimacing:
